version: '3.7'

services:
    ts-node-docker:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        env_file:
            - .env-docker
        volumes:
            - ./src:/home/node/app/src
            - ./nodemon.json:/home/node/app/nodemon.json
        container_name: lecture-back-end
        expose:
            - '4000'
        ports:
            - '4000:4000'
        command: npm run dev

    mongo:
        image: mongo:latest
        ports:
            - 27017:27017
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: tcss460
            MONGO_INITDB_ROOT_PASSWORD: tcss460
            MONGO_INITDB_DATABASE: tcss460123
        container_name: lecture-mongo
        volumes:
            - ~/apps/mongo:/data
